import type { LintDiagnostic, LLMProvider, VaultConfig } from "../types.js";
import { appendLog, loadManifest, saveManifest, writeWiki } from "../vault.js";
import { contradictionRule } from "./contradiction.js";
import { ALL_RULES } from "./rules.js";

export interface LintOptions {
	/** Run only a specific rule */
	ruleFilter?: string;
	/** LLM provider for AI-powered rules (contradiction detection) */
	provider?: LLMProvider;
	/** Callback for progress updates */
	onProgress?: (msg: string) => void;
}

export interface LintResult {
	diagnostics: LintDiagnostic[];
	errors: number;
	warnings: number;
	infos: number;
}

/**
 * Run lint checks on the wiki.
 */
export async function lintVault(root: string, options: LintOptions = {}): Promise<LintResult> {
	const manifest = await loadManifest(root);

	const rules = options.ruleFilter
		? ALL_RULES.filter((r) => r.name === options.ruleFilter)
		: ALL_RULES;

	const allDiagnostics: LintDiagnostic[] = [];

	for (const rule of rules) {
		options.onProgress?.(`Running ${rule.name} check...`);
		const diagnostics = await rule.fn(root, manifest);
		allDiagnostics.push(...diagnostics);
	}

	// LLM-powered rules (only run when provider is available)
	const shouldRunContradiction =
		options.provider && (!options.ruleFilter || options.ruleFilter === "contradiction");
	if (shouldRunContradiction) {
		options.onProgress?.("Running contradiction check...");
		const contradictions = await contradictionRule(root, manifest, options.provider);
		allDiagnostics.push(...contradictions);
	}

	return {
		diagnostics: allDiagnostics,
		errors: allDiagnostics.filter((d) => d.severity === "error").length,
		warnings: allDiagnostics.filter((d) => d.severity === "warning").length,
		infos: allDiagnostics.filter((d) => d.severity === "info").length,
	};
}

export interface FixResult {
	fixed: number;
	skipped: number;
	errors: string[];
}

/**
 * Fix lint issues that are marked as fixable.
 * - `missing`: creates stub wiki articles for frequently-referenced topics
 * - `stale`: recompiles pending sources (requires provider + config)
 */
export async function fixLintIssues(
	root: string,
	diagnostics: LintDiagnostic[],
	provider?: LLMProvider,
	config?: VaultConfig,
): Promise<FixResult> {
	const result: FixResult = { fixed: 0, skipped: 0, errors: [] };
	const fixable = diagnostics.filter((d) => d.fixable);

	const missingIssues = fixable.filter((d) => d.rule === "missing");
	const staleIssues = fixable.filter((d) => d.rule === "stale");

	// Fix missing: create stub articles
	if (missingIssues.length > 0) {
		const manifest = await loadManifest(root);

		for (const d of missingIssues) {
			const match = d.message.match(/^"([^"]+)"/);
			if (!match) continue;

			const slug = match[1];
			const title = slug
				.split("-")
				.map((w) => w.charAt(0).toUpperCase() + w.slice(1))
				.join(" ");

			const stub = `---
title: "${title}"
slug: "${slug}"
category: topic
tags: []
sources: []
---

# ${title}

*This article was auto-generated by \`kib lint --fix\`. Add content by ingesting sources about this topic and running \`kib compile\`.*
`;

			try {
				await writeWiki(root, `topics/${slug}.md`, stub);
				const now = new Date().toISOString();
				manifest.articles[slug] = {
					hash: "",
					createdAt: now,
					lastUpdated: now,
					derivedFrom: [],
					backlinks: [],
					forwardLinks: [],
					tags: [],
					summary: "",
					wordCount: 0,
					category: "topic",
				};
				result.fixed++;
			} catch (err) {
				result.errors.push(`Failed to create ${slug}: ${(err as Error).message}`);
			}
		}

		manifest.stats.totalArticles = Object.keys(manifest.articles).length;
		await saveManifest(root, manifest);
	}

	// Fix stale: recompile pending sources
	if (staleIssues.length > 0) {
		if (!provider || !config) {
			result.skipped += staleIssues.length;
			result.errors.push("Skipped stale fixes — LLM provider required. Set an API key and retry.");
		} else {
			try {
				const { compileVault } = await import("../compile/compiler.js");
				await compileVault(root, provider, config, { force: false });
				result.fixed += staleIssues.length;
			} catch (err) {
				result.skipped += staleIssues.length;
				result.errors.push(`Compile failed: ${(err as Error).message}`);
			}
		}
	}

	if (result.fixed > 0) {
		await appendLog(root, "lint-fix", `${result.fixed} issues fixed`);
	}

	return result;
}
